"""
SQLAlchemy models for RAG analysis storage
"""

from sqlalchemy import Column, Integer, String, Float, DateTime, Text, ForeignKey, JSON
from sqlalchemy.dialects.postgresql import UUID, ARRAY
from sqlalchemy.orm import relationship
from datetime import datetime
from app.db.database import Base
import uuid


class AIAnalysis(Base):
    """Stores AI diagnosis and RAG analysis results"""
    __tablename__ = "ai_analyses"

    id = Column(Integer, primary_key=True, index=True)
    patient_id = Column(UUID(as_uuid=True), ForeignKey("patients.id"), nullable=False)
    
    # Diagnosis info
    disease = Column(String(255), nullable=False)  # "acne_vulgaire"
    disease_label = Column(String(255), nullable=False)  # "Acné vulgaire"
    confidence = Column(Float, nullable=False)  # 0.0-1.0
    
    # Relationships
    clinical_questions = relationship("ClinicalQuestion", back_populates="analysis", cascade="all, delete-orphan")
    treatments = relationship("Treatment", back_populates="analysis", cascade="all, delete-orphan")
    alerts = relationship("Alert", back_populates="analysis", cascade="all, delete-orphan")
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class ClinicalQuestion(Base):
    """Clinical questions generated by RAG pipeline"""
    __tablename__ = "clinical_questions"

    id = Column(Integer, primary_key=True, index=True)
    analysis_id = Column(Integer, ForeignKey("ai_analyses.id"), nullable=False)
    
    question = Column(Text, nullable=False)
    question_order = Column(Integer, default=0)  # Order in sequence
    
    analysis = relationship("AIAnalysis", back_populates="clinical_questions")
    
    created_at = Column(DateTime, default=datetime.utcnow)


class Treatment(Base):
    """Treatment recommendations from RAG"""
    __tablename__ = "treatments"

    id = Column(Integer, primary_key=True, index=True)
    analysis_id = Column(Integer, ForeignKey("ai_analyses.id"), nullable=False)
    
    name = Column(String(255), nullable=False)  # "Isotrétinoïne"
    description = Column(Text, nullable=False)
    dosage = Column(String(255))  # "0.5-1mg/kg"
    duration = Column(String(255))  # "16-24 weeks"
    contraindications = Column(JSON)  # List of contraindications
    
    analysis = relationship("AIAnalysis", back_populates="treatments")
    
    created_at = Column(DateTime, default=datetime.utcnow)


class Alert(Base):
    """Safety alerts and contraindications"""
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, index=True)
    analysis_id = Column(Integer, ForeignKey("ai_analyses.id"), nullable=False)
    
    alert_type = Column(String(50), nullable=False)  # "CONTRAINDICATION" | "WARNING" | "CAUTION"
    message = Column(Text, nullable=False)
    severity = Column(String(20), nullable=False)  # "HIGH" | "MEDIUM" | "LOW"
    
    analysis = relationship("AIAnalysis", back_populates="alerts")
    
    created_at = Column(DateTime, default=datetime.utcnow)


class KnowledgeChunk(Base):
    """Stores knowledge base chunks with embeddings for RAG retrieval"""
    __tablename__ = "knowledge_chunks"

    id = Column(Integer, primary_key=True, index=True)
    disease = Column(String(255), nullable=False, index=True)
    content = Column(Text, nullable=False)
    
    # Embedding vector (pgvector)
    embedding = Column(ARRAY(Float), nullable=True)  # Vector for semantic search
    
    created_at = Column(DateTime, default=datetime.utcnow)

    class Config:
        schema_extra = {
            "example": {
                "disease": "acne_vulgaire",
                "content": "Acne vulgaris treatment...",
                "embedding": [0.1, 0.2, ..., 0.5]
            }
        }
